# You can use this file to create a conda environment for this pipeline:
#   conda env update -f environment.yml -n base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nomkl
  - fastqc=0.11.8
  - emboss=6.6.0
  - tbb=2020.2
  - bowtie2=2.3.4.3
  - bwa=0.7.17
  - trim-galore=0.4.5
  - kraken=1.1
  - krona=2.7.1
  - samtools=1.9
  - bedtools=2.27.1
  - picard=2.19.0
  - spades=3.13.0
  - quast=5.0.2
  - multiqc=1.6
  - qualimap=2.2.2a
  - preseq=2.0.3
  - perl-bioperl=1.7.2
  - minced=0.3.0
  - prokka=1.12
  - diamond=0.9
  - biopython=1.73
  - seaborn=0.10.1
  - cgecore=1.5.1
  - seqtk=1.3
  - khmer=2.1.2
  - bioconda::cutadapt=2
  - bioconda::gatk=3.8
  - anaconda::tabulate=0.8.3
  - bioconda::nextflow=20.10.0
  - bioconda::checkm-genome=1.1.2
  - bioconda::muscle=3.8.1551
  - bioconda::gblocks=0.91b
  - bioconda::fasttree=2.1.10
  - bioconda::fastani=1.1
  - bioconda::roary=3.13.0
  - bioconda::ncbi-genome-download=0.3.0
  - bioconda::scoary=1.6.16
  - ete3=3.1.2
  - bioconda::drep=2.6.2
  - bioconda::comparem=0.1.1
  - bioconda::eukcc=0.2
  - bioconda::kpal=2.1
  - conda-forge::opentsne=0.5
  - conda-forge::graphviz=2.40
  - conda-forge::typer=0.2.1
  - conda-forge::colorama=0.4.3
  - conda-forge::shellingham=1.3.2
  - conda-forge::click-spinner=0.1.10
  - conda-forge::tqdm=4.46.0
  - ruby=2.6.5
  - r-base=3.6
  - r-essentials=3.6
  - r-rcurl
  - bioconductor-rhtslib
  - bioconductor-biobase
  - bioconductor-biocgenerics
  - bioconductor-s4vectors
  - bioconductor-iranges
  - bioconductor-zlibbioc
  - bioconductor-genomicranges
  - bioconductor-xvector
  - bioconductor-biocparallel
  - bioconductor-genomeinfodb
  - bioconductor-biostrings
  - bioconductor-summarizedexperiment
  - bioconductor-rsamtools
  - bioconductor-genomicalignments
  - bioconductor-delayedarray
  - bioconductor-dnacopy
