version: 2.0
jobs:
 build:
   docker:
     - image: gongyh/scgs
   steps:
     - checkout
     - run:
         name: install-nextflow
         command: export NXF_VER='19.01.0' && wget -qO- get.nextflow.io | bash && ln -s $PWD/nextflow /usr/local/bin/nextflow
     - run:
         name: install-GraphViz
         command: apt-get install -y graphviz
     - run:
         name: test-hasref
         command: mkdir -p tests && cd tests && nextflow run ../ -profile test -w work1 --outdir result1 -name hasref && cd ..
     - run:
         name: test-denovo
         command: mkdir -p tests && cd tests && nextflow run ../ -profile test_denovo -w work2 --outdir result2 -name denovo && cd ..
