version: 2.0
jobs:
 build:
   docker:
     - image: gongyh/scgs:dev
   steps:
     - checkout
     - run:
         name: The First Step
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
