version: 2.0
jobs:
 build:
   docker:
     - image: quay.io/gongyh/nf-core-scgs:latest
   environment:
     - GIT_LFS_SKIP_SMUDGE: 1
   steps:
     - checkout
     - run:
         name: test
         environment:
           NXF_VER: 21.03.0-edge
         command: |
           mkdir -p tests && cd tests
           curl -fsSL https://get.nextflow.io | bash
           ./nextflow run ../ -profile test
         no_output_timeout: 30m
     - store_artifacts:
         path: /root/project/tests/result/pipeline_info
     - store_artifacts:
         path: /root/project/tests/.nextflow.log
         destination: nextflow-log
